apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-messages-pvc
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed

