image:
  debug: true

replicaCount: 3

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"

externalAccess:
  enabled: false
  autoDiscovery:
    enabled: true

kraft:
  enabled: true
  replicas: 3
  zookeeper:
    enabled: false

extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "true"
  - name: KAFKA_CFG_PROCESS_ROLES
    value: "controller,broker"
  - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
    value: "0@kafka-release-controller-0.kafka-release-controller-headless.kafka.svc.cluster.local:9093,1@kafka-release-controller-1.kafka-release-controller-headless.kafka.svc.cluster.local:9093,2@kafka-release-controller-2.kafka-release-controller-headless.kafka.svc.cluster.local:9093"
  - name: KAFKA_CFG_NODE_ID
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: KAFKA_CFG_ADVERTISED_LISTENERS
    value: "PLAINTEXT://kafka-release.kafka.svc.cluster.local:9092"
  - name: KAFKA_CFG_LISTENERS
    value: "PLAINTEXT://:9092,CONTROLLER://:9093"
  - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
    value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
    value: "PLAINTEXT"
  - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
    value: "CONTROLLER"
  - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
    value: "true"  # Allow topic deletion
  - name: KAFKA_CFG_AUTO_CREATE_TOPIC_ENABLE
    value: "true"  # Allow automatic topic creation
  - name: KAFKA_CFG_LOG_RETENTION_HOURS
    value: "168"  # Retain logs for 7 days
  - name: KAFKA_CFG_LOG_SEGMENT_BYTES
    value: "1073741824"  # 1GB log segment size
  - name: KAFKA_CFG_MESSAGE_MAX_BYTES
    value: "10485760"  # Allow 10MB max message size
  - name: KAFKA_CFG_NUM_PARTITIONS
    value: "3"  # Default topic partition count
  - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
    value: "3"  # Replication
